apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: games-db-pvc
  namespace: microservices
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: standard-rwo

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: games-db
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: games-db
  template:
    metadata:
      labels:
        app: games-db
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        ports:
        - containerPort: 3306
          name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "rootpass123"
        - name: MYSQL_DATABASE
          value: "games_db"
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: GAMES_DB_USERNAME
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: GAMES_DB_PASSWORD
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          exec:
            command:
            - mysqladmin
            - ping
            - -h
            - localhost
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - mysqladmin
            - ping
            - -h
            - localhost
          initialDelaySeconds: 10
          periodSeconds: 5
      volumes:
      - name: mysql-data
        persistentVolumeClaim:
          claimName: games-db-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: games-db
  namespace: microservices
spec:
  selector:
    app: games-db
  ports:
  - port: 3306
    targetPort: 3306
  type: ClusterIP
