apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-microservice
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-microservice
  template:
    metadata:
      labels:
        app: users-microservice
    spec:
      containers:
        - name: users-microservice
          image: troyroy/belote_users_microservice:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "docker"
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: USERS_DB_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: USERS_DB_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: USERS_DB_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: JWT_SECRET
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: ADMIN_PASSWORD
            - name: KEYCLOAK_SERVER_URL
              value: "http://keycloak:8080"
            - name: KEYCLOAK_REALM
              value: "belote-game"
            - name: KEYCLOAK_CLIENT_ID
              value: "belote-backend"
            - name: KEYCLOAK_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: KEYCLOAK_CLIENT_SECRET
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "250m"
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 300
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 240
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 5

---
apiVersion: v1
kind: Service
metadata:
  name: users-microservice
  namespace: microservices
spec:
  selector:
    app: users-microservice
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP